### [Unprotected] Register a new user
# Allowed for everyone to enable initial account creation
POST {{host}}/api/users/register
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "role": "ROLE_ADMIN"
}

> {% client.global.set("auth_token", response.body.token); %}


### [Protected] Get all registered users
# Requires a valid Bearer Token. Usually restricted to ADMIN role
GET {{host}}/api/users
Authorization: Bearer {{auth_token}}


### [Protected] Get specific user by ID
# Requires a valid Bearer Token
GET {{host}}/api/users/65f1a2b3c4d5e6f7g8h9
Authorization: Bearer {{auth_token}}


### [Protected] Update user details
# Requires a valid Bearer Token. Updates username, password, or role
PUT {{host}}/api/users/65f1a2b3c4d5e6f7g8h9
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "kevin_updated",
  "password": "newpassword123",
  "role": "ROLE_ADMIN"
}


### [Protected] Delete a user
# Requires a valid Bearer Token. Critical operation
DELETE {{host}}/api/users/65f1a2b3c4d5e6f7g8h9
Authorization: Bearer {{auth_token}}